# Generated by Django 5.0.2 on 2024-03-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdecorator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdecorator',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userdecorator',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], default=3, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userdecorator',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
